version: '2'
services:
  myblog-postgresql:
    image: postgres:12.1
    # volumes:
    #     - ~/volumes/jhipster/myblog/postgresql/:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=myblog
      - POSTGRES_PASSWORD=
    ports:
      - 5432:5432
